server:
  port: 9001
  servlet:
    context-path: /ship

spring:
  application:
    name: ship-center
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liu.code.shipcenter.entity
  configuration:
    map-underscore-to-camel-case: true
