spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_wms?serverTimezone=UTC
    username: root
    password: lxf6206288

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.131:8848
        namespace: 764257e3-6593-4ea5-b10f-b818ce17aa5b
    alibaba:
      seata:
        tx-service-group: wc-fescar-service-group
  # 添加该 microservice 到 springcloud sleuth 的监控
  zipkin:
    base-url: http://192.168.152.131:9411
  sleuth:
    sampler:
      # [0,1],采样率,1代表全部采集
      probability: 1


