server:
  port: 5001
  servlet:
    context-path: /account

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?serverTimezone=UTC
    username: root
    password: lxf6206288

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.131:8848
        namespace: 764257e3-6593-4ea5-b10f-b818ce17aa5b
    alibaba:
      seata:
        tx-service-group: ac-fescar-service-group

  zipkin:
    base-url: http://192.168.152.131:9411
  sleuth:
    sampler:
      probability: 1

  application:
    name: account-center

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liu.code.accountcenter.entity
  configuration:
    map-underscore-to-camel-case: true
